[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlopscourse"
version = "0.1.0"
description = "A sample MLOps project"
dependencies = [
    # List your dependencies here
]
